.PHONY: all install build serve

all: install serve

# Install the tools and dependencies
install:
	npm install

# Builds the final website
build:
	npm run -- build

# Builds the website + automatically rebuilds + reloads the web browser
serve:
	npm run -- start
