apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 3
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: gcr.io/zeebe-io/worker:{{.ImageTag}}
          imagePullPolicy: Always
          env:
            - name: JDK_JAVA_OPTIONS
              value: >-
                -Dapp.brokerUrl=http://{{.ServiceName}}:26500
                -Dapp.brokerRestUrl=http://{{.ServiceName}}:8080
                -Dapp.preferRest=false
                -Dapp.auth.type=OAUTH
                -Dzeebe.client.requestTimeout=62000
                -Dapp.worker.capacity=10
                -Dapp.worker.pollingDelay={{.PollingDelay}}
                -Dapp.worker.completionDelay=50ms
                -XX:+HeapDumpOnOutOfMemoryError
            - name: CAMUNDA_LOG_LEVEL
              value: "debug"
            - name: ZEEBE_AUTHORIZATION_SERVER_URL
              value: {{.AuthServer}}
            - name: ZEEBE_TOKEN_AUDIENCE
              value: {{.Audience}}
            - name: ZEEBE_CLIENT_ID
              value: {{.ClientId}}
            - name: ZEEBE_CLIENT_SECRET
              value: {{.ClientSecret}}
            - name: SPRING_PROFILES_ACTIVE
              value: "worker"
            - name: ZEEBE_AUTH_METHOD
              value: {{if .AuthServer}}"oidc"{{else}}"none"{{end}}
            - name: CAMUNDA_CLIENT_GRPC_ADDRESS
              value: http://{{.ServiceName}}:26500
            - name: CAMUNDA_CLIENT_REST_ADDRESS
              value: http://{{.ServiceName}}:8080
            - name: CAMUNDA_CLIENT_PREFER_REST_OVER_GRPC
              value: "false"
            - name: CAMUNDA_CLIENT_REQUEST_TIMEOUT
              value: "62s"
            - name: LOAD_TESTER_WORKER_CAPACITY
              value: "10"
            - name: LOAD_TESTER_WORKER_POLLING_DELAY
              value: "{{.PollingDelay}}"
            - name: LOAD_TESTER_WORKER_COMPLETION_DELAY
              value: "50ms"
            - name: LOGGING_LEVEL_IO_CAMUNDA_ZEEBE
              value: INFO
            - name: LOAD_TESTER_LOG_APPENDER
              value: Stackdriver
            - name: LOAD_TESTER_LOG_STACKDRIVER_SERVICENAME
              value: load-tester
            - name: LOAD_TESTER_LOG_STACKDRIVER_SERVICEVERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 4
              memory: 2Gi
            requests:
              cpu: 1
              memory: 512Mi
