apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 3
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: gcr.io/zeebe-io/worker:{{ imageTag }}
          imagePullPolicy: Always
          env:
            - name: JDK_JAVA_OPTIONS
              value: >-
                -Dapp.brokerUrl=zeebe-service:26500
                -Dzeebe.client.requestTimeout=62000
                -Dapp.worker.capacity=10
                -Dapp.worker.pollingDelay={{ pollingDelay }}
                -Dapp.worker.completionDelay=50ms
                -XX:+HeapDumpOnOutOfMemoryError
            - name: LOG_LEVEL
              value: "debug"
          resources:
            limits:
              cpu: 4
              memory: 2Gi
            requests:
              cpu: 1
              memory: 512Mi
