apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 3
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: gcr.io/zeebe-io/worker:{{.ImageTag}}
          imagePullPolicy: Always
          env:
            - name: JDK_JAVA_OPTIONS
              value: >-
                -Dapp.brokerUrl=http://zeebe-service:26500
                -Dapp.auth.type=OAUTH
                -Dzeebe.client.requestTimeout=62000
                -Dapp.worker.capacity=10
                -Dapp.worker.pollingDelay={{.PollingDelay}}
                -Dapp.worker.completionDelay=50ms
                -XX:+HeapDumpOnOutOfMemoryError
            - name: LOG_LEVEL
              value: "debug"
            - name: CAMUNDA_AUTHORIZATION_SERVER_URL
              value: {{.AuthServer}}
            - name: CAMUNDA_TOKEN_AUDIENCE
              value: {{.Audience}}
            - name: CAMUNDA_CLIENT_ID
              value: {{.ClientId}}
            - name: CAMUNDA_CLIENT_SECRET
              value: {{.ClientSecret}}
          resources:
            limits:
              cpu: 4
              memory: 2Gi
            requests:
              cpu: 1
              memory: 512Mi
