name: Build Chaos Blog

on:
  workflow_dispatch: { }
  push:
    branches:
      - "**"
    paths:
      - chaos-days/**
      - .github/workflows/buildChaosBlog.yml

jobs:
  build:
    name: Build the documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          cd chaos-days
          npm config set legacy-peer-deps
          npm install
      - name: Build
        run: |
          cd chaos-days
          npm run build
  auto-merge:
    name: Auto-merge dependency PRs
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.repository == 'zeebe-io/zeebe-chaos' && (github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]')
    permissions:
      checks: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - id: merge
        name: Merge PR
        run: gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GITHUB_TOKEN: "${{ secrets.AUTO_MERGE_GITHUB_TOKEN }}"
