name: Build Chaos Blog

on:
  workflow_dispatch: { }
  push:
    branches:
      - "*"
    paths:
      - chaos-days/**
      - .github/workflows/buildChaosBlog.yml

jobs:
  build:
    name: Build the documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          cd chaos-days
          npm config set legacy-peer-deps
          npm install
      - name: Build
        run: |
          cd chaos-days
          npm run build
